spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationDB
    username: postgres
    password: 18ll_2002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: com.aimed.linkedin.*

server:
  port: 9040
  servlet:
    context-path: /notifications




