spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2

            - id: posts-service
              uri: lb://POSTS-SERVICE
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

            - id: connections-service
              uri: lb://CONNECTIONS-SERVICE
              predicates:
                - Path=/api/v1/connections/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

server:
  port: 8080

jwt:
  secretKey: dfasdlfh343f335nkf98knfksdnfsnfa9fwehfonfoinfew902nefn02lnff

eureka:
  instance:
    prefer-ip-address: true     # this was added because the eureka server was earlier picking up
                                # the hostname in place of the ip address and was giving error while API execution
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: INFO
