spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postsDB
    username: postgres
    password: 18ll_2002   # set during PostgreSQL installation
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9010
